### ISSUE TITLE
adb 权限替换反和谐文件

### ISSUE THREAD

**Issue by Ayin-a** [BlueArchiveCN/Anti-Harmony#11]
1 需要拥有python环境我用的是3.9.1
2解压下边文件到一个英文路径
[adb替换反和谐文件.zip](https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/files/12261553/adb.zip)
3然后连接上你的手机 并且允许你的手机adb调试
4最后在文件根目录输入python tihuan.py
小孩子不懂事 乱传着玩的

**Comment by Ayin-a** [comment]
/storage/emulated/0/Android/data/com.RoamingStar.BlueArchive/files/AssetBundls/
安卓路径(如果不是请自行更改

**Comment by Ayin-a** [comment]
> 1 需要拥有python环境我用的是3.9.1 2解压下边文件到一个英文路径 [adb替换反和谐文件.zip](https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/files/12261553/adb.zip) 3然后连接上你的手机 并且允许你的手机adb调试 4最后在文件根目录输入python tihuan.py 小孩子不懂事 乱传着玩的

[adb替换反和谐文件新.zip](https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/files/12265926/adb.zip)
新文件

**Comment by 360NENZ** [comment]
建议转到[**ADB**](https://github.com/BlueArchiveCN/Anti-Harmony-ADB)
