### ISSUE TITLE
iOS版的文件名和仓库里的不一样

### ISSUE THREAD

**Issue by MamboJiang** [BlueArchiveCN/Anti-Harmony#5]
如图，不知道为什么但是文件名就是不一样，所以不会被替换掉，游戏内也就不起效果
文件大小也有些差别
当然，只把文件名改了也没用（
而iOS的BA日服和国际服都不让在越狱状态下进
还能有什么办法吗qwq
<img width="1010" alt="截屏2023-08-03 20 07 04" src="https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/assets/60293500/8e7f24d2-55b6-46b9-b23f-78d2f61afd98">
<img width="1020" alt="截屏2023-08-03 20 06 47" src="https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/assets/60293500/ca04abb2-f89c-4bc4-9a4c-f048df21c3dc">
<img width="1019" alt="截屏2023-08-03 20 06 35" src="https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/assets/60293500/d10f9121-591b-41b2-baf4-28ced9b07d64">
<img width="1036" alt="截屏2023-08-03 20 06 22" src="https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/assets/60293500/9069e82c-7ea1-4b73-bfaa-5a27b784559f">

**Comment by yemoyu123** [comment]
> 如图，不知道为什么但是文件名就是不一样，所以不会被替换掉，游戏内也就不起效果 文件大小也有些差别 当然，只把文件名改了也没用（ 而iOS的BA日服和国际服都不让在越狱状态下进 还能有什么办法吗qwq <img alt="截屏2023-08-03 20 07 04" width="1010" src="https://user-images.githubusercontent.com/60293500/258106544-8e7f24d2-55b6-46b9-b23f-78d2f61afd98.png"> <img alt="截屏2023-08-03 20 06 47" width="1020" src="https://user-images.githubusercontent.com/60293500/258106554-ca04abb2-f89c-4bc4-9a4c-f048df21c3dc.png"> <img alt="截屏2023-08-03 20 06 35" width="1019" src="https://user-images.githubusercontent.com/60293500/258106558-d10f9121-591b-41b2-baf4-28ced9b07d64.png"> <img alt="截屏2023-08-03 20 06 22" width="1036" src="https://user-images.githubusercontent.com/60293500/258106564-9069e82c-7ea1-4b73-bfaa-5a27b784559f.png">

请把文件发送给我

**Comment by MamboJiang** [comment]
[BAiOS.zip](https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/files/12255977/BAiOS.zip)

**Comment by yemoyu123** [comment]
> [BAiOS.zip](https://github.com/yemoyu123/bluearchiveChinaServerAnti-Harmony/files/12255977/BAiOS.zip)

好的，仓库已进行更新

**Comment by MamboJiang** [comment]
谢谢！！
